# Generated by Django 3.2.14 on 2022-08-29 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('men', 'MEN'), ('women', 'WOMEN')], default=1, max_length=10, verbose_name='Пол'),
        ),
    ]
