# Generated by Django 3.2.14 on 2022-08-29 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('men', 'Мужчина'), ('women', 'Женщина')], default=2, max_length=10, verbose_name='Пол'),
        ),
    ]
