# Generated by Django 3.2.14 on 2022-09-01 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_profile_growth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='growth',
            field=models.IntegerField(blank=True, verbose_name='Рост'),
        ),
    ]
