# Generated by Django 3.2.14 on 2022-09-03 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_profile_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='growth',
            field=models.IntegerField(blank=True, default='', null=True, verbose_name='Рост'),
        ),
    ]
