# Generated by Django 3.2.14 on 2022-09-03 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_alter_profile_growth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='growth',
            field=models.IntegerField(blank=True, default=0, verbose_name='Рост'),
        ),
    ]
