# Generated by Django 3.2.14 on 2022-08-10 18:51

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EveryWeekReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Дата отчета')),
                ('weight', models.IntegerField(verbose_name='Вес')),
                ('neck', models.IntegerField(verbose_name='Шея')),
                ('waist', models.IntegerField(verbose_name='Бедра')),
                ('hips', models.IntegerField(verbose_name='Талия')),
                ('side_view', models.ImageField(upload_to='user_photo', verbose_name='Вид сбоку')),
                ('front_view', models.ImageField(upload_to='user_photo', verbose_name='Вид спереди')),
                ('back_view', models.ImageField(upload_to='user_photo', verbose_name='Вид сзади')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Участник')),
            ],
            options={
                'verbose_name': 'Ежеднедельные отчеты',
                'verbose_name_plural': 'Ежеднедельный отчет',
            },
        ),
        migrations.CreateModel(
            name='EveryDayReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Дата отчета')),
                ('food', models.TextField(blank=True, verbose_name='Питание')),
                ('weight', models.IntegerField(verbose_name='Вес утром')),
                ('steps', models.IntegerField(verbose_name='Шаги')),
                ('critical_days', models.BooleanField(default=False, verbose_name='Критические дни')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Участник')),
            ],
            options={
                'verbose_name': 'Ежедневные отчеты',
                'verbose_name_plural': 'Ежедневный отчет',
            },
        ),
    ]
