# Generated by Django 3.2.14 on 2022-08-10 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='everyweekreport',
            name='back_view',
            field=models.ImageField(blank=True, upload_to='user_photo', verbose_name='Вид сзади'),
        ),
        migrations.AlterField(
            model_name='everyweekreport',
            name='front_view',
            field=models.ImageField(blank=True, upload_to='user_photo', verbose_name='Вид спереди'),
        ),
        migrations.AlterField(
            model_name='everyweekreport',
            name='side_view',
            field=models.ImageField(blank=True, upload_to='user_photo', verbose_name='Вид сбоку'),
        ),
    ]
