# Generated by Django 3.2.14 on 2022-08-13 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20220810_2320'),
    ]

    operations = [
        migrations.AddField(
            model_name='everydayreport',
            name='link',
            field=models.CharField(default='ссылка', max_length=250, verbose_name='Ссылка на отчет'),
        ),
    ]
