# Generated by Django 3.2.14 on 2022-08-18 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20220819_0013'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название страницы')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
                ('text', models.TextField(verbose_name='Содержание')),
                ('image', models.ImageField(upload_to='media/author')),
            ],
            options={
                'verbose_name': 'Страницы',
                'verbose_name_plural': 'Страницу',
            },
        ),
        migrations.CreateModel(
            name='PageImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/reviews', verbose_name='Фото отзывы')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.page', verbose_name='Страница')),
            ],
        ),
    ]
