# Generated by Django 3.2.14 on 2022-08-18 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20220819_0140'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pageimage',
            options={'verbose_name': 'Фото отзыв', 'verbose_name_plural': 'Фото отзывы'},
        ),
        migrations.AlterField(
            model_name='everyweekreport',
            name='back_view',
            field=models.ImageField(blank=True, upload_to='user_photo', verbose_name='Вид сзади'),
        ),
        migrations.AlterField(
            model_name='everyweekreport',
            name='front_view',
            field=models.ImageField(blank=True, upload_to='user_photo', verbose_name='Вид спереди'),
        ),
        migrations.AlterField(
            model_name='everyweekreport',
            name='side_view',
            field=models.ImageField(blank=True, upload_to='user_photo', verbose_name='Вид сбоку'),
        ),
        migrations.AlterField(
            model_name='page',
            name='image',
            field=models.ImageField(blank=True, upload_to='author', verbose_name='Изображение автора'),
        ),
        migrations.AlterField(
            model_name='pageimage',
            name='image',
            field=models.ImageField(upload_to='reviews', verbose_name='Фото отзывы'),
        ),
    ]
