# Generated by Django 3.2.14 on 2022-08-18 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20220819_0209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pageimage',
            name='image',
        ),
        migrations.AddField(
            model_name='pageimage',
            name='image_after',
            field=models.ImageField(blank=True, upload_to='reviews', verbose_name='Фото после'),
        ),
        migrations.AddField(
            model_name='pageimage',
            name='image_before',
            field=models.ImageField(blank=True, upload_to='reviews', verbose_name='Фото до'),
        ),
    ]
