# Generated by Django 3.2.14 on 2022-08-26 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20220819_0219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='everydayreport',
            name='food',
        ),
    ]
