# Generated by Django 3.2.14 on 2022-08-26 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_everydayreport_food'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='everyweekreport',
            options={'verbose_name': 'Еженедельные отчеты', 'verbose_name_plural': 'Еженедельный отчет'},
        ),
    ]
