# Generated by Django 3.2.14 on 2022-08-26 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='everydayreport',
            name='file',
            field=models.FileField(blank=True, upload_to='user_file', verbose_name='Файл отчета'),
        ),
        migrations.AlterField(
            model_name='everydayreport',
            name='link',
            field=models.CharField(blank=True, default='ссылка', max_length=250, verbose_name='Ссылка на отчет'),
        ),
    ]
