# Generated by Django 3.2.14 on 2022-08-30 21:59

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20220827_0123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='text',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Содержание'),
        ),
    ]
