# Generated by Django 3.2.14 on 2022-08-31 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_page_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='everyweekreport',
            options={'ordering': ['-date'], 'verbose_name': 'Еженедельные отчеты', 'verbose_name_plural': 'Еженедельный отчет'},
        ),
        migrations.RemoveField(
            model_name='pageimage',
            name='image_after',
        ),
    ]
