# Generated by Django 3.2.14 on 2022-09-01 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20220831_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageimage',
            name='image_before',
            field=models.ImageField(blank=True, upload_to='reviews', verbose_name='Фото'),
        ),
    ]
