# Generated by Django 3.2.14 on 2022-09-01 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_pageimage_image_before'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='everyweekreport',
            options={'verbose_name': 'Еженедельные отчеты', 'verbose_name_plural': 'Еженедельный отчет'},
        ),
    ]
