# Generated by Django 3.2.14 on 2022-08-26 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_user'),
        ('tasks', '0003_auto_20220827_0023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plank',
            name='week_report',
        ),
        migrations.AddField(
            model_name='plank',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.profile', verbose_name='Участник'),
        ),
    ]
