# Generated by Django 3.2.14 on 2022-09-01 16:16

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_auto_20220827_0028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='text',
            field=ckeditor.fields.RichTextField(verbose_name='Задание'),
        ),
    ]
